name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  
  workflow_dispatch:  
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2

      - name: Gerar a cobrinha com os commits
        uses: Platane/snk@master
        with:
          github_user_name: oseiasbarreto
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Publicar no branch "output"
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
